version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: mongod --replSet rs0

  mongo-init:
    image: mongo:6
    depends_on:
      - mongodb
    entrypoint: ["bash", "-c", "sleep 5 && mongo --host mongodb:27017 --eval 'rs.initiate()'"]

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mongodb
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/voteApp

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
